<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Department;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $departments = [
            // Argentina
            ['country' => 'Argentina', 'name' => 'Buenos Aires'],
            ['country' => 'Argentina', 'name' => 'Catamarca'],
            ['country' => 'Argentina', 'name' => 'Chaco'],
            ['country' => 'Argentina', 'name' => 'Chubut'],
            ['country' => 'Argentina', 'name' => 'Córdoba'],
            ['country' => 'Argentina', 'name' => 'Corrientes'],
            ['country' => 'Argentina', 'name' => 'Entre Ríos'],
            ['country' => 'Argentina', 'name' => 'Formosa'],
            ['country' => 'Argentina', 'name' => 'Jujuy'],
            ['country' => 'Argentina', 'name' => 'La Pampa'],
            ['country' => 'Argentina', 'name' => 'La Rioja'],
            ['country' => 'Argentina', 'name' => 'Mendoza'],
            ['country' => 'Argentina', 'name' => 'Misiones'],
            ['country' => 'Argentina', 'name' => 'Neuquén'],
            ['country' => 'Argentina', 'name' => 'Río Negro'],
            ['country' => 'Argentina', 'name' => 'Salta'],
            ['country' => 'Argentina', 'name' => 'San Juan'],
            ['country' => 'Argentina', 'name' => 'San Luis'],
            ['country' => 'Argentina', 'name' => 'Santa Cruz'],
            ['country' => 'Argentina', 'name' => 'Santa Fe'],
            ['country' => 'Argentina', 'name' => 'Santiago del Estero'],
            ['country' => 'Argentina', 'name' => 'Tierra del Fuego'],
            ['country' => 'Argentina', 'name' => 'Tucumán'],
            // Bolivia
            ['country' => 'Bolivia', 'name' => 'Beni'],
            ['country' => 'Bolivia', 'name' => 'Chuquisaca'],
            ['country' => 'Bolivia', 'name' => 'Cochabamba'],
            ['country' => 'Bolivia', 'name' => 'La Paz'],
            ['country' => 'Bolivia', 'name' => 'Oruro'],
            ['country' => 'Bolivia', 'name' => 'Pando'],
            ['country' => 'Bolivia', 'name' => 'Potosí'],
            ['country' => 'Bolivia', 'name' => 'Santa Cruz'],
            ['country' => 'Bolivia', 'name' => 'Tarija'],
            // Brasil
            ['country' => 'Brasil', 'name' => 'Acre'],
            ['country' => 'Brasil', 'name' => 'Alagoas'],
            ['country' => 'Brasil', 'name' => 'Amapá'],
            ['country' => 'Brasil', 'name' => 'Amazonas'],
            ['country' => 'Brasil', 'name' => 'Bahia'],
            ['country' => 'Brasil', 'name' => 'Ceará'],
            ['country' => 'Brasil', 'name' => 'Distrito Federal'],
            ['country' => 'Brasil', 'name' => 'Espírito Santo'],
            ['country' => 'Brasil', 'name' => 'Goiás'],
            ['country' => 'Brasil', 'name' => 'Maranhão'],
            ['country' => 'Brasil', 'name' => 'Mato Grosso'],
            ['country' => 'Brasil', 'name' => 'Mato Grosso do Sul'],
            ['country' => 'Brasil', 'name' => 'Minas Gerais'],
            ['country' => 'Brasil', 'name' => 'Pará'],
            ['country' => 'Brasil', 'name' => 'Paraíba'],
            ['country' => 'Brasil', 'name' => 'Paraná'],
            ['country' => 'Brasil', 'name' => 'Pernambuco'],
            ['country' => 'Brasil', 'name' => 'Piauí'],
            ['country' => 'Brasil', 'name' => 'Rio de Janeiro'],
            ['country' => 'Brasil', 'name' => 'Rio Grande do Norte'],
            ['country' => 'Brasil', 'name' => 'Rio Grande do Sul'],
            ['country' => 'Brasil', 'name' => 'Rondônia'],
            ['country' => 'Brasil', 'name' => 'Roraima'],
            ['country' => 'Brasil', 'name' => 'Santa Catarina'],
            ['country' => 'Brasil', 'name' => 'São Paulo'],
            ['country' => 'Brasil', 'name' => 'Sergipe'],
            ['country' => 'Brasil', 'name' => 'Tocantins'],
            // Chile
            ['country' => 'Chile', 'name' => 'Arica y Parinacota'],
            ['country' => 'Chile', 'name' => 'Tarapacá'],
            ['country' => 'Chile', 'name' => 'Antofagasta'],
            ['country' => 'Chile', 'name' => 'Atacama'],
            ['country' => 'Chile', 'name' => 'Coquimbo'],
            ['country' => 'Chile', 'name' => 'Valparaíso'],
            ['country' => 'Chile', 'name' => 'Metropolitana de Santiago'],
            ['country' => 'Chile', 'name' => 'Libertador General Bernardo O\'Higgins'],
            ['country' => 'Chile', 'name' => 'Maule'],
            ['country' => 'Chile', 'name' => 'Ñuble'],
            ['country' => 'Chile', 'name' => 'Biobío'],
            ['country' => 'Chile', 'name' => 'La Araucanía'],
            ['country' => 'Chile', 'name' => 'Los Ríos'],
            ['country' => 'Chile', 'name' => 'Los Lagos'],
            ['country' => 'Chile', 'name' => 'Aysén del General Carlos Ibáñez del Campo'],
            ['country' => 'Chile', 'name' => 'Magallanes y de la Antártica Chilena'],
            // Colombia
            ['country' => 'Colombia', 'name' => 'Amazonas'],
            ['country' => 'Colombia', 'name' => 'Antioquia'],
            ['country' => 'Colombia', 'name' => 'Arauca'],
            ['country' => 'Colombia', 'name' => 'Atlántico'],
            ['country' => 'Colombia', 'name' => 'Bolívar'],
            ['country' => 'Colombia', 'name' => 'Boyacá'],
            ['country' => 'Colombia', 'name' => 'Caldas'],
            ['country' => 'Colombia', 'name' => 'Caquetá'],
            ['country' => 'Colombia', 'name' => 'Casanare'],
            ['country' => 'Colombia', 'name' => 'Cauca'],
            ['country' => 'Colombia', 'name' => 'Cesar'],
            ['country' => 'Colombia', 'name' => 'Chocó'],
            ['country' => 'Colombia', 'name' => 'Córdoba'],
            ['country' => 'Colombia', 'name' => 'Cundinamarca'],
            ['country' => 'Colombia', 'name' => 'Distrito Capital de Bogotá'],
            ['country' => 'Colombia', 'name' => 'Guainía'],
            ['country' => 'Colombia', 'name' => 'Guaviare'],
            ['country' => 'Colombia', 'name' => 'Huila'],
            ['country' => 'Colombia', 'name' => 'La Guajira'],
            ['country' => 'Colombia', 'name' => 'Magdalena'],
            ['country' => 'Colombia', 'name' => 'Meta'],
            ['country' => 'Colombia', 'name' => 'Nariño'],
            ['country' => 'Colombia', 'name' => 'Norte de Santander'],
            ['country' => 'Colombia', 'name' => 'Putumayo'],
            ['country' => 'Colombia', 'name' => 'Quindío'],
            ['country' => 'Colombia', 'name' => 'Risaralda'],
            ['country' => 'Colombia', 'name' => 'Santander'],
            ['country' => 'Colombia', 'name' => 'Sucre'],
            ['country' => 'Colombia', 'name' => 'Tolima'],
            ['country' => 'Colombia', 'name' => 'Valle del Cauca'],
            ['country' => 'Colombia', 'name' => 'Vaupés'],
            ['country' => 'Colombia', 'name' => 'Vichada'],
            // Costa Rica
            ['country' => 'Costa Rica', 'name' => 'San José'],
            ['country' => 'Costa Rica', 'name' => 'Alajuela'],
            ['country' => 'Costa Rica', 'name' => 'Cartago'],
            ['country' => 'Costa Rica', 'name' => 'Heredia'],
            ['country' => 'Costa Rica', 'name' => 'Guanacaste'],
            ['country' => 'Costa Rica', 'name' => 'Puntarenas'],
            ['country' => 'Costa Rica', 'name' => 'Limón'],
            // Cuba
            ['country' => 'Cuba', 'name' => 'Pinar del Río'],
            ['country' => 'Cuba', 'name' => 'Artemisa'],
            ['country' => 'Cuba', 'name' => 'La Habana'],
            ['country' => 'Cuba', 'name' => 'Mayabeque'],
            ['country' => 'Cuba', 'name' => 'Matanzas'],
            ['country' => 'Cuba', 'name' => 'Villa Clara'],
            ['country' => 'Cuba', 'name' => 'Sancti Spíritus'],
            ['country' => 'Cuba', 'name' => 'Ciego de Ávila'],
            ['country' => 'Cuba', 'name' => 'Camagüey'],
            ['country' => 'Cuba', 'name' => 'Las Tunas'],
            ['country' => 'Cuba', 'name' => 'Holguín'],
            ['country' => 'Cuba', 'name' => 'Granma'],
            ['country' => 'Cuba', 'name' => 'Santiago de Cuba'],
            ['country' => 'Cuba', 'name' => 'Guantánamo'],
            // Ecuador
            ['country' => 'Ecuador', 'name' => 'Azuay'],
            ['country' => 'Ecuador', 'name' => 'Bolívar'],
            ['country' => 'Ecuador', 'name' => 'Cañar'],
            ['country' => 'Ecuador', 'name' => 'Carchi'],
            ['country' => 'Ecuador', 'name' => 'Chimborazo'],
            ['country' => 'Ecuador', 'name' => 'Cotopaxi'],
            ['country' => 'Ecuador', 'name' => 'El Oro'],
            ['country' => 'Ecuador', 'name' => 'Esmeraldas'],
            ['country' => 'Ecuador', 'name' => 'Galápagos'],
            ['country' => 'Ecuador', 'name' => 'Guayas'],
            ['country' => 'Ecuador', 'name' => 'Imbabura'],
            ['country' => 'Ecuador', 'name' => 'Loja'],
            ['country' => 'Ecuador', 'name' => 'Los Ríos'],
            ['country' => 'Ecuador', 'name' => 'Manabí'],
            ['country' => 'Ecuador', 'name' => 'Morona Santiago'],
            ['country' => 'Ecuador', 'name' => 'Napo'],
            ['country' => 'Ecuador', 'name' => 'Orellana'],
            ['country' => 'Ecuador', 'name' => 'Pastaza'],
            ['country' => 'Ecuador', 'name' => 'Pichincha'],
            ['country' => 'Ecuador', 'name' => 'Santa Elena'],
            ['country' => 'Ecuador', 'name' => 'Santo Domingo de los Tsáchilas'],
            ['country' => 'Ecuador', 'name' => 'Sucumbíos'],
            ['country' => 'Ecuador', 'name' => 'Tungurahua'],
            ['country' => 'Ecuador', 'name' => 'Zamora Chinchipe'],
            // El Salvador
            ['country' => 'El Salvador', 'name' => 'Ahuachapán'],
            ['country' => 'El Salvador', 'name' => 'Santa Ana'],
            ['country' => 'El Salvador', 'name' => 'Sonsonate'],
            ['country' => 'El Salvador', 'name' => 'Chalatenango'],
            ['country' => 'El Salvador', 'name' => 'La Libertad'],
            ['country' => 'El Salvador', 'name' => 'San Salvador'],
            ['country' => 'El Salvador', 'name' => 'Cuscatlán'],
            ['country' => 'El Salvador', 'name' => 'Cabañas'],
            ['country' => 'El Salvador', 'name' => 'La Paz'],
            ['country' => 'El Salvador', 'name' => 'San Vicente'],
            ['country' => 'El Salvador', 'name' => 'Usulután'],
            ['country' => 'El Salvador', 'name' => 'Morazán'],
            // Guatemala
            ['country' => 'Guatemala', 'name' => 'Guatemala'],
            ['country' => 'Guatemala', 'name' => 'Progreso'],
            ['country' => 'Guatemala', 'name' => 'Sacatepéquez'],
            ['country' => 'Guatemala', 'name' => 'Chimaltenango'],
            ['country' => 'Guatemala', 'name' => 'Escuintla'],
            ['country' => 'Guatemala', 'name' => 'Santa Rosa'],
            ['country' => 'Guatemala', 'name' => 'Sololá'],
            ['country' => 'Guatemala', 'name' => 'Totonicapán'],
            ['country' => 'Guatemala', 'name' => 'Quetzaltenango'],
            ['country' => 'Guatemala', 'name' => 'Huehuetenango'],
            ['country' => 'Guatemala', 'name' => 'San Marcos'],
            ['country' => 'Guatemala', 'name' => 'Retalhuleu'],
            ['country' => 'Guatemala', 'name' => 'Baja Verapaz'],
            ['country' => 'Guatemala', 'name' => 'Alta Verapaz'],
            ['country' => 'Guatemala', 'name' => 'Petén'],
            ['country' => 'Guatemala', 'name' => 'Izabal'],
            ['country' => 'Guatemala', 'name' => 'Jalapa'],
            ['country' => 'Guatemala', 'name' => 'Jutiapa'],
            // Honduras
            ['country' => 'Honduras', 'name' => 'Cortés'],
            ['country' => 'Honduras', 'name' => 'Atlántida'],
            ['country' => 'Honduras', 'name' => 'Comayagua'],
            ['country' => 'Honduras', 'name' => 'La Paz'],
            ['country' => 'Honduras', 'name' => 'Copán'],
            ['country' => 'Honduras', 'name' => 'Ocotepeque'],
            ['country' => 'Honduras', 'name' => 'Santa Bárbara'],
            ['country' => 'Honduras', 'name' => 'Lempira'],
            ['country' => 'Honduras', 'name' => 'Intibucá'],
            ['country' => 'Honduras', 'name' => 'Yoro'],
            ['country' => 'Honduras', 'name' => 'Francisco Morazán'],
            ['country' => 'Honduras', 'name' => 'El Paraíso'],
            ['country' => 'Honduras', 'name' => 'Islas de la Bahía'],
            ['country' => 'Honduras', 'name' => 'Gracias a Dios'],
            // México
            ['country' => 'México', 'name' => 'Aguascalientes'],
            ['country' => 'México', 'name' => 'Baja California'],
            ['country' => 'México', 'name' => 'Baja California Sur'],
            ['country' => 'México', 'name' => 'Campeche'],
            ['country' => 'México', 'name' => 'Chiapas'],
            ['country' => 'México', 'name' => 'Chihuahua'],
            ['country' => 'México', 'name' => 'Colima'],
            ['country' => 'México', 'name' => 'Ciudad de México'],
            ['country' => 'México', 'name' => 'Durango'],
            ['country' => 'México', 'name' => 'Estado de México'],
            ['country' => 'México', 'name' => 'Guanajuato'],
            ['country' => 'México', 'name' => 'Guerrero'],
            ['country' => 'México', 'name' => 'Hidalgo'],
            ['country' => 'México', 'name' => 'Jalisco'],
            ['country' => 'México', 'name' => 'Michoacán'],
            ['country' => 'México', 'name' => 'Morelos'],
            ['country' => 'México', 'name' => 'Nayarit'],
            ['country' => 'México', 'name' => 'Nuevo León'],
            ['country' => 'México', 'name' => 'Oaxaca'],
            ['country' => 'México', 'name' => 'Puebla'],
            ['country' => 'México', 'name' => 'Querétaro'],
            ['country' => 'México', 'name' => 'Quintana Roo'],
            ['country' => 'México', 'name' => 'San Luis Potosí'],
            ['country' => 'México', 'name' => 'Sinaloa'],
            ['country' => 'México', 'name' => 'Sonora'],
            ['country' => 'México', 'name' => 'Tabasco'],
            ['country' => 'México', 'name' => 'Tamaulipas'],
            ['country' => 'México', 'name' => 'Tlaxcala'],
            ['country' => 'México', 'name' => 'Veracruz'],
            ['country' => 'México', 'name' => 'Yucatán'],
            ['country' => 'México', 'name' => 'Zacatecas'],
            // Nicaragua
            ['country' => 'Nicaragua', 'name' => 'Boaco'],
            ['country' => 'Nicaragua', 'name' => 'Carazo'],
            ['country' => 'Nicaragua', 'name' => 'Chinandega'],
            ['country' => 'Nicaragua', 'name' => 'Chontales'],
            ['country' => 'Nicaragua', 'name' => 'Estelí'],
            ['country' => 'Nicaragua', 'name' => 'Granada'],
            ['country' => 'Nicaragua', 'name' => 'Jinotega'],
            ['country' => 'Nicaragua', 'name' => 'León'],
            ['country' => 'Nicaragua', 'name' => 'Madriz'],
            ['country' => 'Nicaragua', 'name' => 'Managua'],
            ['country' => 'Nicaragua', 'name' => 'Masaya'],
            ['country' => 'Nicaragua', 'name' => 'Matagalpa'],
            ['country' => 'Nicaragua', 'name' => 'Nueva Segovia'],
            ['country' => 'Nicaragua', 'name' => 'Rivas'],
            ['country' => 'Nicaragua', 'name' => 'Río San Juan'],
            ['country' => 'Nicaragua', 'name' => 'Costa Caribe Norte'],
            ['country' => 'Nicaragua', 'name' => 'Costa Caribe Sur'],
            // Panamá
            ['country' => 'Panamá', 'name' => 'Bocas del Toro'],
            ['country' => 'Panamá', 'name' => 'Coclé'],
            ['country' => 'Panamá', 'name' => 'Colón'],
            ['country' => 'Panamá', 'name' => 'Darién'],
            ['country' => 'Panamá', 'name' => 'Herrera'],
            ['country' => 'Panamá', 'name' => 'Los Santos'],
            ['country' => 'Panamá', 'name' => 'Panamá'],
            ['country' => 'Panamá', 'name' => 'Panamá Oeste'],
            ['country' => 'Panamá', 'name' => 'San Blas'],
            ['country' => 'Panamá', 'name' => 'Veraguas'],
            // Paraguay
            ['country' => 'Paraguay', 'name' => 'Asunción'],
            ['country' => 'Paraguay', 'name' => 'Alto Paraguay'],
            ['country' => 'Paraguay', 'name' => 'Alto Paraná'],
            ['country' => 'Paraguay', 'name' => 'Amambay'],
            ['country' => 'Paraguay', 'name' => 'Caaguazú'],
            ['country' => 'Paraguay', 'name' => 'Caazapá'],
            ['country' => 'Paraguay', 'name' => 'Canindeyú'],
            ['country' => 'Paraguay', 'name' => 'Centralidad'],
            ['country' => 'Paraguay', 'name' => 'Concepción'],
            ['country' => 'Paraguay', 'name' => 'Cordillera'],
            ['country' => 'Paraguay', 'name' => 'Guairá'],
            ['country' => 'Paraguay', 'name' => 'Itapúa'],
            ['country' => 'Paraguay', 'name' => 'Misiones'],
            ['country' => 'Paraguay', 'name' => 'Ñeembucú'],
            ['country' => 'Paraguay', 'name' => 'Paraguarí'],
            // Perú
            ['country' => 'Perú', 'name' => 'Amazonas'],
            ['country' => 'Perú', 'name' => 'Ancash'],
            ['country' => 'Perú', 'name' => 'Apurímac'],
            ['country' => 'Perú', 'name' => 'Arequipa'],
            ['country' => 'Perú', 'name' => 'Ayacucho'],
            ['country' => 'Perú', 'name' => 'Cajamarca'],
            ['country' => 'Perú', 'name' => 'Callao'],
            ['country' => 'Perú', 'name' => 'Cusco'],
            ['country' => 'Perú', 'name' => 'Huancavelica'],
            ['country' => 'Perú', 'name' => 'Huánuco'],
            ['country' => 'Perú', 'name' => 'Ica'],
            ['country' => 'Perú', 'name' => 'Junín'],
            ['country' => 'Perú', 'name' => 'La Libertad'],
            ['country' => 'Perú', 'name' => 'Lambayeque'],
            ['country' => 'Perú', 'name' => 'Limá'],
            ['country' => 'Perú', 'name' => 'Loreto'],
            ['country' => 'Perú', 'name' => 'Madre de Dios'],
            ['country' => 'Perú', 'name' => 'Moquegua'],
            ['country' => 'Perú', 'name' => 'Pasco'],
            ['country' => 'Perú', 'name' => 'Piura'],
            ['country' => 'Perú', 'name' => 'Puno'],
            ['country' => 'Perú', 'name' => 'San Martín'],
            ['country' => 'Perú', 'name' => 'Tacna'],
            ['country' => 'Perú', 'name' => 'Tumbes'],
            ['country' => 'Perú', 'name' => 'Ucayali'],
            // República Dominicana
            ['country' => 'República Dominicana', 'name' => 'Azua'],
            ['country' => 'República Dominicana', 'name' => 'Bahoruco'],
            ['country' => 'República Dominicana', 'name' => 'Barahona'],
            ['country' => 'República Dominicana', 'name' => 'Dajabón'],
            ['country' => 'República Dominicana', 'name' => 'Distrito Nacional'],
            ['country' => 'República Dominicana', 'name' => 'Duarte'],
            ['country' => 'República Dominicana', 'name' => 'Elías Piña'],
            ['country' => 'República Dominicana', 'name' => 'El Seibo'],
            ['country' => 'República Dominicana', 'name' => 'Espaillat'],
            ['country' => 'República Dominicana', 'name' => 'Independencia'],
            ['country' => 'República Dominicana', 'name' => 'La Altagracia'],
            ['country' => 'República Dominicana', 'name' => 'La Romana'],
            ['country' => 'República Dominicana', 'name' => 'La Vega'],
            ['country' => 'República Dominicana', 'name' => 'María Trinidad Sánchez'],
            ['country' => 'República Dominicana', 'name' => 'Monseñor Nouel'],
            ['country' => 'República Dominicana', 'name' => 'Monte Cristi'],
            ['country' => 'República Dominicana', 'name' => 'Monte Plata'],
            ['country' => 'República Dominicana', 'name' => 'Montecristi'],
            ['country' => 'República Dominicana', 'name' => 'Pedernales'],
            ['country' => 'República Dominicana', 'name' => 'Peravia'],
            ['country' => 'República Dominicana', 'name' => 'Puerto Plata'],
            ['country' => 'República Dominicana', 'name' => 'Salcedo'],
            ['country' => 'República Dominicana', 'name' => 'Samaná'],
            ['country' => 'República Dominicana', 'name' => 'San Cristóbal'],
            ['country' => 'República Dominicana', 'name' => 'San Juan'],
            ['country' => 'República Dominicana', 'name' => 'San Pedro de Macorís'],
            ['country' => 'República Dominicana', 'name' => 'Sánchez Ramírez'],
            ['country' => 'República Dominicana', 'name' => 'Santiago'],
            ['country' => 'República Dominicana', 'name' => 'Santiago Rodríguez'],
            ['country' => 'República Dominicana', 'name' => 'Santo Domingo'],
            ['country' => 'República Dominicana', 'name' => 'Valverde'],
            // Uruguay
            ['country' => 'Uruguay', 'name' => 'Artigas'],
            ['country' => 'Uruguay', 'name' => 'Canelones'],
            ['country' => 'Uruguay', 'name' => 'Cerro Largo'],
            ['country' => 'Uruguay', 'name' => 'Colonia'],
            ['country' => 'Uruguay', 'name' => 'Durazno'],
            ['country' => 'Uruguay', 'name' => 'Flores'],
            ['country' => 'Uruguay', 'name' => 'Florida'],
            ['country' => 'Uruguay', 'name' => 'Lavalleja'],
            ['country' => 'Uruguay', 'name' => 'Maldonado'],
            ['country' => 'Uruguay', 'name' => 'Montevideo'],
            ['country' => 'Uruguay', 'name' => 'Paysandú'],
            ['country' => 'Uruguay', 'name' => 'Río Negro'],
            ['country' => 'Uruguay', 'name' => 'Rivera'],
            ['country' => 'Uruguay', 'name' => 'Rocha'],
            ['country' => 'Uruguay', 'name' => 'Salto'],
            ['country' => 'Uruguay', 'name' => 'San José'],
            ['country' => 'Uruguay', 'name' => 'Soriano'],
            ['country' => 'Uruguay', 'name' => 'Tacuarembó'],
            ['country' => 'Uruguay', 'name' => 'Treinta y Tres'],
            // Venezuela
            ['country' => 'Venezuela', 'name' => 'Amazonas'],
            ['country' => 'Venezuela', 'name' => 'Anzoátegui'],
            ['country' => 'Venezuela', 'name' => 'Apure'],
            ['country' => 'Venezuela', 'name' => 'Aragua'],
            ['country' => 'Venezuela', 'name' => 'Barinas'],
            ['country' => 'Venezuela', 'name' => 'Bolívar'],
            ['country' => 'Venezuela', 'name' => 'Carabobo'],
            ['country' => 'Venezuela', 'name' => 'Cojedes'],
            ['country' => 'Venezuela', 'name' => 'Delta Amacuro'],
            ['country' => 'Venezuela', 'name' => 'Dependencias Federales'],
            ['country' => 'Venezuela', 'name' => 'Distrito Federal'],
            ['country' => 'Venezuela', 'name' => 'Falcón'],
            ['country' => 'Venezuela', 'name' => 'Guárico'],
            ['country' => 'Venezuela', 'name' => 'Lara'],
            ['country' => 'Venezuela', 'name' => 'Mérida'],
            ['country' => 'Venezuela', 'name' => 'Miranda'],
            ['country' => 'Venezuela', 'name' => 'Monagas'],
            ['country' => 'Venezuela', 'name' => 'Nueva Esparta'],
            ['country' => 'Venezuela', 'name' => 'Portuguesa'],
            ['country' => 'Venezuela', 'name' => 'Sucre'],
            ['country' => 'Venezuela', 'name' => 'Táchira'],
            ['country' => 'Venezuela', 'name' => 'Trujillo'],
            ['country' => 'Venezuela', 'name' => 'Vargas'],
            ['country' => 'Venezuela', 'name' => 'Yaracuy'],
            ['country' => 'Venezuela', 'name' => 'Zulia'],
        ];

        foreach ($departments as $dept) {
            $country = Country::where('name', $dept['country'])->first();
            if ($country) {
                Department::create([
                    'name' => $dept['name'],
                    'country_id' => $country->id,
                ]);
            }
        }
    }
}
